### ISSUE TITLE
java 15?

### ISSUE THREAD

**Issue by licker2689** [patrick-choe/mojang-spigot-remapper#1]
Required by:
         project : > io.github.patrick.remapper:io.github.patrick.remapper.gradle.plugin:1.2.0
      > No matching variant of io.github.patrick-choe:mojang-spigot-remapper:1.2.0 was found. The consumer was configured to find a runtime of a library compatible with Java 15, packaged as a jar, and its dependencies declared externally but:
          - Variant 'apiElements' capability io.github.patrick-choe:mojang-spigot-remapper:1.2.0 declares a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares an API of a component compatible with Java 17 and the consumer needed a runtime of a component compatible with Java 15
          - Variant 'runtimeElements' capability io.github.patrick-choe:mojang-spigot-remapper:1.2.0 declares a runtime of a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component compatible with Java 17 and the consumer needed a component compatible with Java 15

must it be java 17?

자바 17이여야 하지 않나요?

**Comment by patrick-choe** [comment]
mojang-spigot-remapper 라이브러리는 Java 1.8 버전을 타겟으로 컴파일되었으며, 사용하는 라이브러리들은 각각
 - kotlin-stdlib: Java 1.6
 - SpecialSource: Java 1.7

버전으로 컴파일되어있습니다. gradle에서 사용중인 java 버전 문제이지 않을까 조심스럽게 추측해보면서, jdk 버전을 바꾸면 해결되지 않을까 싶습니다.
