### ISSUE TITLE
mojang-spigot-remapper fails on plugins targeted for Java 21

### ISSUE THREAD

**Issue by klugemonkey** [patrick-choe/mojang-spigot-remapper#3]
mojang-spigot-remapper fails to remap plugins targeted for Spigot 1.20.5 since it requires Java 21 code.  The 1.4.0 release of mojang-spigot-remapper uses an out of date implementation of net.md-5:SpecialSource that doesn't support Java 21 code.   The gradle.properties should be update to use the 1.11.4 version of SpecialSource in order to avoid unsupported class file major version 65 errors that prevent remapping.

**Comment by gmitch215** [comment]
Submitted a PR @ https://github.com/patrick-choe/mojang-spigot-remapper/pull/4. See when the owner comes online.

**Comment by patrick-choe** [comment]
I'll push it to gradle plugin server in few hrs thank you so much!
